### PR TITLE
Routing

### PR DESCRIPTION
**Pull request by MattKetmo**
Hello,

What about completing this bootstrap project with some routing components.
Here is a copy of the `@routes` annotation by @hadrienl (from his [blog post about ngNewRouter](https://blog.hadrien.eu/2015/06/05/angularjs-nouveau-routeur/)).

It could be nice also to separate those decorators in a separate lib to easily include them in any project. What do you think?

### CODE REVIEW

**Comment by hadrienl** [comment]
I think it's not enough generic to add this decorator. One should use ngRouter or uiRouter instead of the new router.

**Comment by zewa666** [comment]
Oh man my french is really bad, haven't used it for years, but as far as I understood and also looking at the examples I tend to agree that maybe in the meantime people should still focus on ngRouter or even better uiRouter as the implementation of the newRouter doesn't feel right atm. Let's see how it progresses, closing this issue for now, but we can open it up later if the newRouter is more tending towards a final release

**Comment by zewa666** [comment]
@MattKetmo I've created a new branch with a demo for how you could use the simple ngRouter. It's kinda a workaround but works well enough. Still as said I'm not sure whether this belongs into the core of this project.

https://github.com/zewa666/angular_es6/tree/routing-demo

**Comment by MattKetmo** [comment]
Thanks for the example.

I understand the routing part of an Angular app varies according to the library used (ngRouter, ngNewRouter, uiRouter). But this project is not a library to include. It aims to provide an example to bootstrap an Angular app using the latest _technologies_ and best practices available (ES6, components, decorators, …). If people want es6 but no decorators or want a different structure then they can just delete or replace it. 

I even consider this project as a "guide" to create an Angular 1.x app close to what Angular 2 will be (to ease the migration). That's why using ngNewRouter might make sense (although I have no idea how it will be used in Angular 2).

**Comment by hadrienl** [comment]
Just fork it ;)

New router is not as good as I told in my post. I thought it was as advanced as aurelia one but it can't have child routes. That's why I'm always using uiRouter for my new project. And I'm seriously thinking about migrating to aurelia as soon as possible. So no, there is no better choice. New router is experimental, uiRouter is the most advanced but third part and ngRouter is the official one.

**Comment by zewa666** [comment]
@MattKetmo first of all thank you for the kind words. I appreciate that this project helps other developers to get going with the latest ES6/ES7 technology and a solid project structure.

That said though, focusing on the router is a focus on an additional plugin/module which is not the core of angular itself. Looking through forums/blogs I'm pretty sure still a large amount is and will continue to use UI-Router. The newRouter is nowhere near complete and Angular politics make it hard to estimate whether new breaking changes will be involved. Also when you look at the official repo you will see a kind of downtime of 3-4 months. So I feel pretty uncomfortable to include something thats nowhere near done.

As @hadrienl suggested though, always feel free to create a fork, or maybe even better provide an additional Angular Module, which can be incorporated into this structure. That way the user only has to `jspm install github:YOURREPO` and than leverage the newRouter implementation. Other implementations could be provided the same way.

EDIT:
Also if you want to discuss this further, please open up a new issue so we can continue the discussion over there

**Comment by hadrienl** [comment]
A new _new-router-decorators.js_ in a dedicated repo would be a nice idea :)

**Comment by MattKetmo** [comment]
Ok. Thanks for your feedback :)

**Pull request closed without merging**
