### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by hadrienl**
- better decorators (see readme)
- bundle task

### CODE REVIEW

**Comment by zewa666** [comment]
Wow very nice, you did a lot of things I was looking forward to add to the example. This is going to turn the example into a really full-fledged solution :+1: 

I'll thoroughly review your changes and test everything next week.

Thanks a lot for your great contribution

**Comment by hadrienl** [comment]
It was very instructive :)

**Comment by zewa666** [comment]
@hadrienl could you tell me whether this is no in final condition? I've started reviewing the PR and found new updates today, so I guess it would be better to wait for your final OK. Besides that I found currently the following issues/ideas:
- Starting the APP I get the following error:

```
TypeError: Cannot read property 'call' of undefined
    at new MainCtrl (main-controller.js:9)
```
- SourceMaps seems not to work anymore, maybe it's related to the new folderstructure
- Why the ES6Shim inside KarmaConfig? Is it because of PhantomJS?
- we need to be able to specify a custom bindToController object as well instead always setting it to true, like

```
bindToController: opts.bindToController || true
```

Besides that, awesome work :+1:
Please give me a short answer to above questions and a short GO when you're done with your work so I can fully review and merge the PR.

**Comment by hadrienl** [comment]
- I can't tell, I don't have any error :/
- Sourcemaps works like a charm: capture d ecran 2015-06-19 16 08 31
- Yes, I needed to include es6shim to make app working in PhantomJS. I don't know why.
- I though the usage of scope should be an unique enpoint to set the list of binded properties.

Have you npm/jspm install ?

For the updates, that's my fault to have PR master branch, then I pushed some new commits in it. But they are related so it's not a problem. I should not push anymore commits for a while.

**Comment by zewa666** [comment]
NPM and JSPM was reinstalled yep. The error is related due to property based decorator injection. As soon as I move them to class based it works.

Sourcemaps now suddenly do work for me as well :)

Yeah shimming PhantomJS is needed as it doesn't understand things like .bind etc.

bindToController has a new option to define it's functionality per property as of v.1.4

**Comment by zewa666** [comment]
ok resolved and fixed

**Comment by zewa666** [comment]
Added also the bindToController option overload. For any further work please rebase from the new master and create another PR

**Comment by hadrienl** [comment]
:+1:

**Pull request merged**
